export const initialChecklistItems = [
  { id: 'c1', process_id: 'op1', task_name: 'Verify I-9 & ID Verification documents', is_complete: true },
  { id: 'c2', process_id: 'op1', task_name: 'Execute Mutual NDA & Intellectual Property Assignment', is_complete: true },
  { id: 'c3', process_id: 'op1', task_name: 'Ship Hardware Workstation (MacBook Pro M3, Monitor)', is_complete: true },
  { id: 'c3_1', process_id: 'op1', task_name: 'Provision SSO, Gmail, Slack & GitHub permissions', is_complete: false },
  { id: 'c3_2', process_id: 'op1', task_name: 'HR Benefit Enrollment (Health Insurance & 401k)', is_complete: false },
  { id: 'c4', process_id: 'op2', task_name: 'Verify I-9 & ID Verification documents', is_complete: true },
  { id: 'c5', process_id: 'op2', task_name: 'Execute Mutual NDA & Intellectual Property Assignment', is_complete: false },
  { id: 'c6', process_id: 'op2', task_name: 'Ship Hardware Workstation (MacBook Pro M3, Monitor)', is_complete: false },
  { id: 'c6_1', process_id: 'op2', task_name: 'Provision SSO, Gmail, Slack & GitHub permissions', is_complete: false },
  { id: 'c7', process_id: 'fp1', task_name: 'Retrieve Corporate Hardware (MacBook Pro, Charger)', is_complete: false },
  { id: 'c8', process_id: 'fp1', task_name: 'Revoke Google Workspace, SSO & AWS accounts', is_complete: false },
  { id: 'c9', process_id: 'fp1', task_name: 'Conduct exit interview with HR Director', is_complete: false },
  { id: 'c9_1', process_id: 'fp1', task_name: 'Process final payroll settlement & expense claims', is_complete: false },
  { id: 'c10', process_id: 'fp2', task_name: 'Retrieve Corporate Hardware (MacBook Pro, Charger)', is_complete: true },
  { id: 'c11', process_id: 'fp2', task_name: 'Revoke Google Workspace, SSO & AWS accounts', is_complete: true },
  { id: 'c12', process_id: 'fp2', task_name: 'Conduct exit interview with HR Director', is_complete: false },
  { id: 'c13', process_id: 'fp2', task_name: 'Process final payroll settlement & expense claims', is_complete: false },
  { id: 'c14', process_id: 'op3', task_name: 'Verify I-9 & ID Verification documents', is_complete: false },
  { id: 'c15', process_id: 'op3', task_name: 'Provision SSO, Gmail, Slack & GitHub permissions', is_complete: false },
  { id: 'c16', process_id: 'fp3', task_name: 'Retrieve Corporate Hardware (Laptop, Charger)', is_complete: false },
  { id: 'c17', process_id: 'fp3', task_name: 'Conduct exit interview with HR Director', is_complete: false },
]
